### ISSUE TITLE
Coniql won't reconnect initially-disconnected PVs

### ISSUE THREAD

**Issue by willrogers** [dls-controls/coniql#22]
A little rabbit hole here.

Coniql does a caget when connecting to PVs to fetch 'meta' values. If the PV is not available an exception will be thrown and the camonitor won't be executed (I expect, but haven't tested).

You can fix this easily enough if you accept PVs won't get meta values if they reconnect subsequently. It would take a little more thinking to fetch meta values on reconnection.

If I do fix this there are some slightly tricky typing questions: e.g. Mypy doesn't like getting an attribute from a `None`, so I wondered about an `AugmentedNone` or similar to avoid lots more code changes.

Then I get to `AugmentedValue` in Aioca. From the comment most of the attributes may not be present, but they are all required in an `AugmentedValue`. But then are optional attributes allowed (as opposed to `Optional` attributes)?

I have now been dragged away from my original fix and I'm not sure of the cleanest way forward. Any ideas?

**Comment by thomascobb** [comment]
I have another issue with the current scheme, it doesn't update metadata (like labels) if they change. I was thinking of maintaining 2 monitors (FORMAT_CTRL and FORMAT_TIME) instead of a get and monitor, which would solve this issue too. Downside is getting twice the amount of data, but I guess I could drop the FORMAT_CTRL monitor if this happened too much (further down the line).

What do you reckon?

**Comment by thomascobb** [comment]
I think EDM does a get then a monitor, and CS-Studio does 2 monitors, but I might be wrong there

**Comment by willrogers** [comment]
Let me double-check: cothread (via libca) requires you to choose `FORMAT_TIME` (which provides timestamp) and `FORMAT_CTRL` (which provides display limits etc). We want both, but timestamp is more obviously important, so we caget to get the CTRL and camonitor to get TIME.

We could set up two monitors so that we maintain updates to everything. However, we are then getting the value twice and in the case of large or fast-updating arrays this could prove expensive. Are you proposing to stop the CTRL monitor dynamically?

Meanwhile JCA with its pure-Java implementation seems to manage to subscribe to both: `CTRL.java` extends `GR.java` extends `TIME.java`.

**Comment by thomascobb** [comment]
Yes, that is correct. @Araneidae or @lyodaom do you know how pure Java JCA might get timestamp with DBR_CTRL but libca doesn't? Is it a client side decision what metadata to get along with the value?

**Comment by Araneidae** [comment]
It's very simple, they must be cheating; Java JCA is probably making two CA requests under the hood.  When you make a CA request you specify the DBR type, which defines the precise data structure returned by CA.  The only DBR types that include timestamp information are the DBR_TIME_... types which don't include any control data.  Have a look in `db_access.h` for details, [here](https://github.com/epicsdeb/epics-base/blob/master/src/ca/client/db_access.h) for example.  You'll see that `epicsTimeStamp` occurs in `dbr_time_...` structures only.

**Comment by thomascobb** [comment]
@willrogers so we could be clever about this, see what the user is asking for (via the request), then make a subscription to STS, CTRL and/or TIME appropriately

**Comment by willrogers** [comment]
There are so many layers in CS-Studio, but: it looks like `JCA_PV.java` creates a TIME monitor and a CTRL monitor. Although `CTRL` extends `TIME`, you just seem to get `null` for the timestamp if you monitor with `CTRL`.

https://github.com/ControlSystemStudio/cs-studio/blob/master/core/base/base-plugins/org.csstudio.vtype.pv/src/org/csstudio/vtype/pv/jca/JCA_PV.java

@Araneidae, what are the implications of creating two monitors on the same PV if it transfers lots of data?

**Comment by Araneidae** [comment]
I suggest you create a `CTRL` monitor with an array length of 1 and maybe set the events mask to just `DBE_PROPERTY`.  With luck this will mean you only get monitor updates when any of the control values change.  Then at the same time create a `TIME` monitor with the usual array size (probably 0 for default) and monitor event mask `DBE_VALUE | DBE_ALARM`.

This way the control monitor will _only_ give you control field updates, and everything else will come through the time monitor which is small.

**Comment by willrogers** [comment]
Yes, here we are: https://epics.anl.gov/base/R3-16/0-docs/CAproto/index.html#monitor-mask

**Comment by willrogers** [comment]
Let me have a look at this today and see where I get to.

**Comment by willrogers** [comment]
What properties should trigger an update for `DBE_PROPERTY`? I am seeing nothing.

I have a python IOC running R3.14.12.7. I am using an `aOut` record.

**Comment by willrogers** [comment]
I cannot see any update to a monitor (whatever mask) from a change of `.EGU` or `.HIHI` (unless the change to `HIHI` causes a change in the alarm state). I have tried a Python IOC and a soft IOC run by epicscorelibs. I am using cothread as a client.

It's certainly possible that I'm missing something ("oh, you're using the wrong record type") but I can't see anything.

**Comment by Araneidae** [comment]
My vague memory is that there are some event trigger bugs with control properties and that monitoring them doesn't fully work.  Does an ordinary `camonitor` of a `.EGU` field work (not that that uses `DBE_PROPERTY` updates).

**Comment by thomascobb** [comment]
Maybe @mdavidsaver could shed some light on why a `DBR_CTRL` monitor with `DBE_PROPERTY` mask doesn't fire when `.EGU` is changed?

**Comment by mdavidsaver** [comment]
What version(s) of Base are involved here?  client and server?

Also, it would be good to get a second opinion from `camonitor -m p PV.EGU`.

**Comment by willrogers** [comment]
Lots of variables here, but I think I see similar behaviour from:

* Server: with pythonIoc on 3.14.12.7 and `softIoc` from epicscorelibs `7.0.4.99.1.2`
* Client: 3.14.12.7 `camonitor -p` - no updates when monitoring either `PV` or `PV.EGU` when changing either `PV` or `PV.EGU`
* Client cothread w/ epicscorelibs `7.0.4.99.1.2`
* Client jca 2.4.4

**Comment by mdavidsaver** [comment]
fyi. A brief history of `DBE_PROPERTY`.  The definition first appears in Base 3.14.11.  However, monitor updates with it where initially only posted by mbbi/mbbo for the enum/choices list.  It wasn't supported by PCAS (and by extension cagateway) until 3.14.12.3 (and there were bugs until fairly recently).  Base 3.15.0.2 introduced the `prop(YES)` annotation in .dbd files, and added automatic posting of `DBE_PROPERTY` when changing a field so marked.  This includes the `EGU` field for the Base record types.  I'm not sure of the status of external record types (eg. motorRecord).

So...  Assuming that `PV` is a Base record type.

>     * Server: with pythonIoc on 3.14.12.7

This server certainly won't be posting `DBE_PROPERTY` for `EGU` changes

>     * `softIoc` from epicscorelibs `7.0.4.99.1.2`

This one should

>     * Client: 3.14.12.7 `camonitor -p`

This client version should understand `DBE_PROPERTY`.

>     * Client cothread w/ epicscorelibs `7.0.4.99.1.2`

This certainly does.

>     * Client jca 2.4.4

I think this does, but I'm not 100% up to date on JCA version numbering.

**Comment by willrogers** [comment]
Thanks for the clarification. I did have a mistake: for my epicscorelibs server I was running `softIoc` from the path when I needed `python -m epicscorelibs.ioc`.

With the newer version of the server I **do** see events for changes to `HIHI` and `EGU`.

**Comment by willrogers** [comment]
Two options then:

1. Time+Value monitor and Ctrl+Value|Alarm|Property monitor
  * Old servers: properties update when value or alarm changes only
  * New servers: properties update when properties change
  * Risk of double-fetch of value
2. Time+Value|Alarm monitor and Ctrl+Property monitor
  * Old servers: properties never update
  * New servers: properties update when properties change
  * More 'correct'; only get what we want

**Comment by thomascobb** [comment]
I'd favour 2, it's no worse than EDM, and seems neater to fetch data in one monitor and metadata in another

**Comment by willrogers** [comment]
Closed by #24
