### ISSUE TITLE
Add prometheus metrics

### ISSUE THREAD

**Issue by aawdls** [dls-controls/coniql#45]
Add a prometheus metrics endpoint that will enable monitoring of state.

Metrics for:
- Number of graphql subscriptions
- Number of unique clients (if possible?)
- Number of CA and PVA monitors
- Count of exceptions / errors - of different types if appropriate
- Number of dropped updates

This will enable better monitoring.

**Comment by AlexanderWells-diamond** [comment]
This has been merged as part of #53
